modLoader="javafml"
loaderVersion="[25,)"
[[mods]]
modId="movingworld"
version="${file.jarVersion}"
displayName="MovingWorld"
description='''
A Library for allowing the movement of collections of blocks and tile entities.
'''